/**
 * This file is **autogenerated** by Python. Any manual changes to it will be
 * OVERWRITTEN!
 */

#ifndef BIGINT_TYPES_H_
#define BIGINT_TYPES_H_

#define AVX_ADD_CHUNK                             0
#define BASIC_ADD_CHUNK                           1
#define BASIC_ADD_OTHER                           2
#define BASIC_ADD_SIZE                            3
#define BASIC_MUL_CHUNK                           4
#define BASIC_MUL_SIZE                            5
#define BIGINT_TYPE_BIG_INT_ABS                   6
#define BIGINT_TYPE_BIG_INT_ADD                   7
#define BIGINT_TYPE_BIG_INT_ADD_MOD               8
#define BIGINT_TYPE_BIG_INT_CHI                   9
#define BIGINT_TYPE_BIG_INT_COMPARE               10
#define BIGINT_TYPE_BIG_INT_COPY                  11
#define BIGINT_TYPE_BIG_INT_CREATE_FROM_CHUNK     12
#define BIGINT_TYPE_BIG_INT_CREATE_FROM_DBL_CHUNK 13
#define BIGINT_TYPE_BIG_INT_CREATE_FROM_HEX       14
#define BIGINT_TYPE_BIG_INT_CREATE_RANDOM         15
#define BIGINT_TYPE_BIG_INT_DIV                   16
#define BIGINT_TYPE_BIG_INT_DIV_MOD               17
#define BIGINT_TYPE_BIG_INT_DIV_REM               18
#define BIGINT_TYPE_BIG_INT_EGCD                  19
#define BIGINT_TYPE_BIG_INT_GET_RES               20
#define BIGINT_TYPE_BIG_INT_INV                   21
#define BIGINT_TYPE_BIG_INT_IS_ODD                22
#define BIGINT_TYPE_BIG_INT_IS_ZERO               23
#define BIGINT_TYPE_BIG_INT_MOD                   24
#define BIGINT_TYPE_BIG_INT_MUL                   25
#define BIGINT_TYPE_BIG_INT_MUL_256               26
#define BIGINT_TYPE_BIG_INT_MUL_MOD               27
#define BIGINT_TYPE_BIG_INT_MUL_SINGLE_CHUNK      28
#define BIGINT_TYPE_BIG_INT_NEG                   29
#define BIGINT_TYPE_BIG_INT_POW                   30
#define BIGINT_TYPE_BIG_INT_PRUNE_LEADING_ZEROS   31
#define BIGINT_TYPE_BIG_INT_SLL_SMALL             32
#define BIGINT_TYPE_BIG_INT_SQUARED               33
#define BIGINT_TYPE_BIG_INT_SQUARED_128           34
#define BIGINT_TYPE_BIG_INT_SQUARED_160           35
#define BIGINT_TYPE_BIG_INT_SQUARED_192           36
#define BIGINT_TYPE_BIG_INT_SQUARED_224           37
#define BIGINT_TYPE_BIG_INT_SQUARED_256           38
#define BIGINT_TYPE_BIG_INT_SQUARED_32            39
#define BIGINT_TYPE_BIG_INT_SQUARED_64            40
#define BIGINT_TYPE_BIG_INT_SQUARED_96            41
#define BIGINT_TYPE_BIG_INT_SQUARED_MOD           42
#define BIGINT_TYPE_BIG_INT_SRL_SMALL             43
#define BIGINT_TYPE_BIG_INT_SUB                   44
#define BIGINT_TYPE_BIG_INT_SUB_MOD               45
#define BIGINT_TYPE_CURVE1174_BIG_INT_ADD_MOD     46
#define BIGINT_TYPE_CURVE1174_BIG_INT_CHI         47
#define BIGINT_TYPE_CURVE1174_BIG_INT_DIV_MOD     48
#define BIGINT_TYPE_CURVE1174_BIG_INT_INV         49
#define BIGINT_TYPE_CURVE1174_BIG_INT_MOD         50
#define BIGINT_TYPE_CURVE1174_BIG_INT_MUL_MOD     51
#define BIGINT_TYPE_CURVE1174_BIG_INT_POW         52
#define BIGINT_TYPE_CURVE1174_BIG_INT_POW_Q_M1_D2 53
#define BIGINT_TYPE_CURVE1174_BIG_INT_POW_Q_M2    54
#define BIGINT_TYPE_CURVE1174_BIG_INT_POW_Q_P1_D4 55
#define BIGINT_TYPE_CURVE1174_BIG_INT_POW_SMALL   56
#define BIGINT_TYPE_CURVE1174_BIG_INT_SQUARED_MOD 57
#define BIGINT_TYPE_CURVE1174_BIG_INT_SUB_MOD     58
#define BIGINT_TYPE_LAST                          59

__attribute__((unused))
static char *big_int_type_names[] = {
    "avx_add_chunk",
    "basic_add_chunk",
    "basic_add_other",
    "basic_add_size",
    "basic_mul_chunk",
    "basic_mul_size",
    "big_int_abs",
    "big_int_add",
    "big_int_add_mod",
    "big_int_chi",
    "big_int_compare",
    "big_int_copy",
    "big_int_create_from_chunk",
    "big_int_create_from_dbl_chunk",
    "big_int_create_from_hex",
    "big_int_create_random",
    "big_int_div",
    "big_int_div_mod",
    "big_int_div_rem",
    "big_int_egcd",
    "big_int_get_res",
    "big_int_inv",
    "big_int_is_odd",
    "big_int_is_zero",
    "big_int_mod",
    "big_int_mul",
    "big_int_mul_256",
    "big_int_mul_mod",
    "big_int_mul_single_chunk",
    "big_int_neg",
    "big_int_pow",
    "big_int_prune_leading_zeros",
    "big_int_sll_small",
    "big_int_squared",
    "big_int_squared_128",
    "big_int_squared_160",
    "big_int_squared_192",
    "big_int_squared_224",
    "big_int_squared_256",
    "big_int_squared_32",
    "big_int_squared_64",
    "big_int_squared_96",
    "big_int_squared_mod",
    "big_int_srl_small",
    "big_int_sub",
    "big_int_sub_mod",
    "curve1174_big_int_add_mod",
    "curve1174_big_int_chi",
    "curve1174_big_int_div_mod",
    "curve1174_big_int_inv",
    "curve1174_big_int_mod",
    "curve1174_big_int_mul_mod",
    "curve1174_big_int_pow",
    "curve1174_big_int_pow_q_m1_d2",
    "curve1174_big_int_pow_q_m2",
    "curve1174_big_int_pow_q_p1_d4",
    "curve1174_big_int_pow_small",
    "curve1174_big_int_squared_mod",
    "curve1174_big_int_sub_mod",
    "BIGINT_TYPE_LAST",
    "big_int_chi"
};

#endif // BIGINT_TYPES_H_
