/**
 * This file is **autogenerated** by Python. Any manual changes to it will be
 * OVERWRITTEN!
 */

#ifndef BIGINT_TYPES_H_
#define BIGINT_TYPES_H_

#define BIGINT_TYPE_BIG_CREATE                    0
#define BIGINT_TYPE_BIG_INT_ABS                   1
#define BIGINT_TYPE_BIG_INT_ADD                   2
#define BIGINT_TYPE_BIG_INT_ADD_MOD               3
#define BIGINT_TYPE_BIG_INT_ALLOC                 4
#define BIGINT_TYPE_BIG_INT_CALLOC                5
#define BIGINT_TYPE_BIG_INT_CHI                   6
#define BIGINT_TYPE_BIG_INT_COMPARE               7
#define BIGINT_TYPE_BIG_INT_COPY                  8
#define BIGINT_TYPE_BIG_INT_CREATE_FROM_DBL_CHUNK 9
#define BIGINT_TYPE_BIG_INT_CREATE_FROM_HEX       10
#define BIGINT_TYPE_BIG_INT_CREATE_RANDOM         11
#define BIGINT_TYPE_BIG_INT_DESTROY               12
#define BIGINT_TYPE_BIG_INT_DIV                   13
#define BIGINT_TYPE_BIG_INT_DIV_MOD               14
#define BIGINT_TYPE_BIG_INT_DIV_REM               15
#define BIGINT_TYPE_BIG_INT_DUPLICATE             16
#define BIGINT_TYPE_BIG_INT_EGCD                  17
#define BIGINT_TYPE_BIG_INT_GET_RES               18
#define BIGINT_TYPE_BIG_INT_INV                   19
#define BIGINT_TYPE_BIG_INT_IS_ODD                20
#define BIGINT_TYPE_BIG_INT_IS_ZERO               21
#define BIGINT_TYPE_BIG_INT_MOD                   22
#define BIGINT_TYPE_BIG_INT_MUL                   23
#define BIGINT_TYPE_BIG_INT_MUL_MOD               24
#define BIGINT_TYPE_BIG_INT_NEG                   25
#define BIGINT_TYPE_BIG_INT_POW                   26
#define BIGINT_TYPE_BIG_INT_PRUNE_LEADING_ZEROS   27
#define BIGINT_TYPE_BIG_INT_SLL_SMALL             28
#define BIGINT_TYPE_BIG_INT_SRL_SMALL             29
#define BIGINT_TYPE_BIG_INT_SUB                   30
#define BIGINT_TYPE_BIG_INT_SUB_MOD               31
#define BIGINT_TYPE_LAST                          32

__attribute__((unused))
static char *big_int_type_names[] = {
    "big_create",
    "big_int_abs",
    "big_int_add",
    "big_int_add_mod",
    "big_int_alloc",
    "big_int_calloc",
    "big_int_chi",
    "big_int_compare",
    "big_int_copy",
    "big_int_create_from_dbl_chunk",
    "big_int_create_from_hex",
    "big_int_create_random",
    "big_int_destroy",
    "big_int_div",
    "big_int_div_mod",
    "big_int_div_rem",
    "big_int_duplicate",
    "big_int_egcd",
    "big_int_get_res",
    "big_int_inv",
    "big_int_is_odd",
    "big_int_is_zero",
    "big_int_mod",
    "big_int_mul",
    "big_int_mul_mod",
    "big_int_neg",
    "big_int_pow",
    "big_int_prune_leading_zeros",
    "big_int_sll_small",
    "big_int_srl_small",
    "big_int_sub",
    "big_int_sub_mod",
    "BIGINT_TYPE_LAST",
    "big_int_chi"
};

#endif // BIGINT_TYPES_H_
