# Official ubuntu docker image
image: ubuntu

# Build and test the project
test:
    stage: test
    before_script:
        - $CI_PROJECT_DIR/scripts/install-check.sh "$CI_PROJECT_DIR/check"
    script:
        - cd $CI_PROJECT_DIR/tests
        - make all
        - $CI_PROJECT_DIR/tests/scripts/run_all_tests.sh
    artifacts:
        paths:
            - "$CI_PROJECT_DIR/tests/logs"
    cache:
        paths:
            - "$CI_PROJECT_DIR/check/"
            - "$CI_PROJECT_DIR/tests/bin/"
            - "$CI_PROJECT_DIR/bin/"
