# Official ubuntu docker image
image: ubuntu

# Build the project
build:
    stage: build
    before_script:
        - apt update && apt -y install build-essential make gcc
    script:
        - make all
    artifacts:
        paths:
            - tests
    cache:
        paths:
            - "tests/src/obj/*.o"
            - "tests/bin/*"
            - "src/obj/*.o"
            - "bin/*"

# Run all tests
test:
    stage: test
    script:
        - ./tests/scripts/run_all_tests.sh
