# Official ubuntu docker image
image: ubuntu

# Build the project
build:
    stage: build
    before_script:
        - $CI_PROJECT_DIR/scripts/install-check.sh
    script:
        - cd $CI_PROJECT_DIR/tests
        - make all
    artifacts:
        paths:
            - "/tmp/check*/"
            - "$CI_PROJECT_DIR/tests/bin/"
            - "$CI_PROJECT_DIR/bin/"
    cache:
        paths:
            - "/tmp/check*/"
            - "$CI_PROJECT_DIR/tests/bin/"
            - "$CI_PROJECT_DIR/bin/"

# Run all tests
test:
    stage: test
    script:
        - $CI_PROJECT_DIR/tests/scripts/run_all_tests.sh
    artifacts:
        paths:
            - tests/logs
