# Official ubuntu docker image
image: ubuntu

# Build the project
build:
    stage: build
    before_script:
        - apt update
            && DEBIAN_FRONTEND=noninteractive apt -y -q install make
                build-essential libtool libsubunit-dev autoconf pkg-config texinfo wget
        - cd /tmp && wget https://github.com/libcheck/check/archive/0.15.2.tar.gz
            && tar xvf 0.15.2.tar.gz && cd check-* && autoreconf --install
            && ./configure --prefix=/usr && make && make check && make install
    script:
        - cd $CI_PROJECT_PATH/tests && make all
    cache:
        paths:
            - "tests/src/obj/*.o"
            - "tests/bin/*"
            - "src/obj/*.o"
            - "bin/*"

# Run all tests
test:
    stage: test
    script:
        - ./tests/scripts/run_all_tests.sh
