# Official ubuntu docker image
image: ubuntu

.install-check-script: &install-check-script
    - apt update
    - DEBIAN_FRONTEND=noninteractive apt -y -q install make
        build-essential libtool libsubunit-dev autoconf pkg-config texinfo wget
    - cd /tmp
    - wget https://github.com/libcheck/check/archive/0.15.2.tar.gz
    - tar xvf 0.15.2.tar.gz && cd check-*
    - autoreconf --install
    - ./configure --prefix=/usr
    - make
    - make check
    - make install

# Build the project
build:
    stage: build
    before_script:
        - [ ! -d /tmp/check-* ] && *install-check-script
    script:
        - cd $CI_PROJECT_DIR/tests
        - make all
    artifacts:
        paths:
            - "/tmp/check*/"
            - "$CI_PROJECT_DIR/tests/bin/"
            - "$CI_PROJECT_DIR/bin/"
    cache:
        paths:
            - "/tmp/check*/"
            - "$CI_PROJECT_DIR/tests/bin/"
            - "$CI_PROJECT_DIR/bin/"

# Run all tests
test:
    stage: test
    script:
        - $CI_PROJECT_DIR/tests/scripts/run_all_tests.sh
    artifacts:
        paths:
            - tests/logs
