/**
 * This file is **autogenerated** by Python. Any manual changes to it will be
 * OVERWRITTEN!
 */

#ifndef BIGINT_TYPES_H_
#define BIGINT_TYPES_H_

#define BIGINT_CURVE1174_TYPE_BIG_INT_MOD         0
#define BIGINT_CURVE1174_TYPE_BIG_INT_ADD_MOD     1
#define BIGINT_CURVE1174_TYPE_BIG_INT_SUB_MOD     2
#define BIGINT_CURVE1174_TYPE_BIG_INT_MUL_MOD     3
#define BIGINT_CURVE1174_TYPE_BIG_INT_DIV_MOD     4
#define BIGINT_CURVE1174_TYPE_BIG_INT_INV         5
#define BIGINT_CURVE1174_TYPE_BIG_INT_POW_SMALL   6
#define BIGINT_CURVE1174_TYPE_BIG_INT_POW         7
#define BIGINT_CURVE1174_TYPE_BIG_INT_POW_1_2     8
#define BIGINT_CURVE1174_TYPE_BIG_INT_CHI         9
#define BIGINT_TYPE_BIG_INT_GET_RES               10
#define BIGINT_TYPE_BIG_INT_PRUNE_LEADING_ZEROS   11
#define BIGINT_TYPE_BIG_INT_CREATE_FROM_CHUNK     12
#define BIGINT_TYPE_BIG_INT_CREATE_FROM_DBL_CHUNK 13
#define BIGINT_TYPE_BIG_INT_CREATE_FROM_HEX       14
#define BIGINT_TYPE_BIG_INT_CREATE_RANDOM         15
#define BIGINT_TYPE_BIG_INT_COPY                  16
#define BIGINT_TYPE_BIG_INT_NEG                   17
#define BIGINT_TYPE_BIG_INT_ABS                   18
#define BIGINT_TYPE_BIG_INT_ADD                   19
#define BIGINT_TYPE_BIG_INT_SUB                   20
#define BIGINT_TYPE_BIG_INT_MUL_SINGLE_CHUNK      21
#define BIGINT_TYPE_BIG_INT_SQUARED               22
#define BIGINT_TYPE_BIG_INT_MUL                   23
#define BIGINT_TYPE_BIG_INT_DEV_REM               24
#define BIGINT_TYPE_BIG_INT_DIV                   25
#define BIGINT_TYPE_BIG_INT_SLL_SMALL             26
#define BIGINT_TYPE_BIG_INT_SRL_SMALL             27
#define BIGINT_TYPE_BIG_INT_MOD                   28
#define BIGINT_TYPE_BIG_INT_ADD_MOD               29
#define BIGINT_TYPE_BIG_INT_SUB_MOD               30
#define BIGINT_TYPE_BIG_INT_MUL_MOD               31
#define BIGINT_TYPE_BIG_INT_SQUARED_MOD           32
#define BIGINT_TYPE_BIG_INT_DIV_MOD               33
#define BIGINT_TYPE_BIG_INT_INV                   34
#define BIGINT_TYPE_BIG_INT_POW                   35
#define BIGINT_TYPE_BIG_INT_IS_ZERO               36
#define BIGINT_TYPE_BIG_INT_IS_ODD                37
#define BIGINT_TYPE_BIG_INT_COMPARE               38
#define BIGINT_TYPE_BIG_INT_EGCD                  39
#define BIGINT_TYPE_BIG_INT_CHI                   40
#define BIGINT_TYPE_LAST                          41

__attribute__((unused))
static char *big_int_type_names[] = {
    "bigint_curve1174_type_big_int_mod",
    "bigint_curve1174_type_big_int_add_mod",
    "bigint_curve1174_type_big_int_sub_mod",
    "bigint_curve1174_type_big_int_mul_mod",
    "bigint_curve1174_type_big_int_div_mod",
    "bigint_curve1174_type_big_int_inv",
    "bigint_curve1174_type_big_int_pow_small",
    "bigint_curve1174_type_big_int_pow",
    "bigint_curve1174_type_big_int_pow_1_2",
    "bigint_curve1174_type_big_int_chi",
    "big_int_get_res",
    "big_int_prune_leading_zeros",
    "big_int_create_from_chunk",
    "big_int_create_from_dbl_chunk",
    "big_int_create_from_hex",
    "big_int_create_random",
    "big_int_copy",
    "big_int_neg",
    "big_int_abs",
    "big_int_add",
    "big_int_sub",
    "big_int_mul_single_chunk",
    "big_int_squared",
    "big_int_mul",
    "big_int_dev_rem",
    "big_int_div",
    "big_int_sll_small",
    "big_int_srl_small",
    "big_int_mod",
    "big_int_add_mod",
    "big_int_sub_mod",
    "big_int_mul_mod",
    "big_int_squared_mod",
    "big_int_div_mod",
    "big_int_inv",
    "big_int_pow",
    "big_int_is_zero",
    "big_int_is_odd",
    "big_int_compare",
    "big_int_egcd",
    "big_int_chi",
    "last"
};

#endif // BIGINT_TYPES_H_
