/**
 * This file is **autogenerated** by Python. Any manual changes to it will be
 * OVERWRITTEN!
 */

#ifndef BIGINT_TYPES_H_
#define BIGINT_TYPES_H_

#define BIGINT_TYPE_BIG_INT_GET_RES               0
#define BIGINT_TYPE_BIG_INT_PRUNE_LEADING_ZEROS   1
#define BIGINT_TYPE_BIG_INT_CREATE_FROM_CHUNK     2
#define BIGINT_TYPE_BIG_INT_CREATE_FROM_DBL_CHUNK 3
#define BIGINT_TYPE_BIG_INT_CREATE_FROM_HEX       4
#define BIGINT_TYPE_BIG_INT_CREATE_RANDOM         5
#define BIGINT_TYPE_BIG_INT_COPY                  6
#define BIGINT_TYPE_BIG_INT_NEG                   7
#define BIGINT_TYPE_BIG_INT_ABS                   8
#define BIGINT_TYPE_BIG_INT_ADD                   9
#define BIGINT_TYPE_BIG_INT_SUB                   10
#define BIGINT_TYPE_BIG_INT_MUL                   11
#define BIGINT_TYPE_BIG_INT_DEV_REM               12
#define BIGINT_TYPE_BIG_INT_DIV                   13
#define BIGINT_TYPE_BIG_INT_SLL_SMALL             14
#define BIGINT_TYPE_BIG_INT_SRL_SMALL             15
#define BIGINT_TYPE_BIG_INT_MOD                   16
#define BIGINT_TYPE_BIG_INT_ADD_MOD               17
#define BIGINT_TYPE_BIG_INT_SUB_MOD               18
#define BIGINT_TYPE_BIG_INT_MUL_MOD               19
#define BIGINT_TYPE_BIG_INT_DIV_MOD               20
#define BIGINT_TYPE_BIG_INT_INV                   21
#define BIGINT_TYPE_BIG_INT_POW                   22
#define BIGINT_TYPE_BIG_INT_IS_ZERO               23
#define BIGINT_TYPE_BIG_INT_IS_ODD                24
#define BIGINT_TYPE_BIG_INT_COMPARE               25
#define BIGINT_TYPE_BIG_INT_EGCD                  26
#define BIGINT_TYPE_BIG_INT_CHI                   27
#define BIGINT_TYPE_LAST                          28

__attribute__((unused))
static char *big_int_type_names[] = {
    "big_int_get_res",
    "big_int_prune_leading_zeros",
    "big_int_create_from_chunk",
    "big_int_create_from_dbl_chunk",
    "big_int_create_from_hex",
    "big_int_create_random",
    "big_int_copy",
    "big_int_neg",
    "big_int_abs",
    "big_int_add",
    "big_int_sub",
    "big_int_mul",
    "big_int_dev_rem",
    "big_int_div",
    "big_int_sll_small",
    "big_int_srl_small",
    "big_int_mod",
    "big_int_add_mod",
    "big_int_sub_mod",
    "big_int_mul_mod",
    "big_int_div_mod",
    "big_int_inv",
    "big_int_pow",
    "big_int_is_zero",
    "big_int_is_odd",
    "big_int_compare",
    "big_int_egcd",
    "big_int_chi",
    "last"
};

#endif // BIGINT_TYPES_H_